(setq Buffer-menu-name-width 60)
(setq auto-save-default nil)
(setq before-save-hook '(whitespace-cleanup))
(setq confirm-nonexistent-file-or-buffer t)
(setq create-lockfiles nil)
(setq css-indent-offset 2)
(setq custom-safe-themes
      '("a27c00821ccfd5a78b01e4f35dc056706dd9ede09a8b90c6955ae6a390eb1c1e" default))
(setq fill-column 79)
(setq git-commit-fill-column 70)
(setq ibuffer-formats
      '((mark modified read-only locked " "
              (name 60 60 :left :elide)
              " " filename-and-process " ")
        (mark " "
              (name 16 -1)
              " " filename)))
(setq indent-tabs-mode nil)
(setq-default indent-tabs-mode nil)
(setq inhibit-startup-screen t)
(setq initial-scratch-message nil)
(setq js-indent-level 2)
(setq kill-ring-max 100)
(setq make-backup-files nil)
(setq mode-require-final-newline 'ask)
(setq require-final-newline 'ask)
(setq python-fill-docstring-style 'django)
(setq recentf-max-saved-items 1000)
(setq show-paren-style 'mixed)
(setq split-height-threshold 0)
(setq tab-width 4)
(setq tar-mode-show-date t)
(setq truncate-partial-width-windows nil)
(setq vc-display-status nil)
(setq enable-recursive-minibuffers t)
(setq minibuffer-depth-indicate-mode t)
(setq tramp-histfile-override "/home/aarne/.tramp_history")
;; (setq display-buffer-alist '((".*" . (display-buffer-same-window (inhibit-same-window . nil)))))
(setq winner-dont-bind-my-keys t)
;
